DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS subscriber_saved_search_subscriptions CASCADE;
DROP TABLE IF EXISTS saved_searches CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS subscribers CASCADE;
DROP TABLE IF EXISTS records CASCADE;
DROP TABLE IF EXISTS papers CASCADE;
DROP TABLE IF EXISTS sources CASCADE;