// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecordService.DataAccess;

#nullable disable

namespace RecordService.Migrations
{
    [DbContext(typeof(PubTrackerDbContext))]
    [Migration("20260926124246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecordService.DataAccess.Entities.RecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Doi")
                        .HasColumnType("text")
                        .HasColumnName("doi");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("records", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.SearchQueryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastDigestSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_digest_sent_at");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<int?>("SourceRecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_record_count");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "TargetUrl")
                        .IsUnique();

                    b.ToTable("search_queries", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.SearchQueryRecordEntity", b =>
                {
                    b.Property<int>("SearchQueryId")
                        .HasColumnType("integer")
                        .HasColumnName("search_query_id");

                    b.Property<int>("RecordId")
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.HasKey("SearchQueryId", "RecordId");

                    b.HasIndex("RecordId");

                    b.ToTable("search_query_records", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.SourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.SourceRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("RecordId")
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("RecordId", "SourceId")
                        .IsUnique();

                    b.ToTable("source_records", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsMarkedForDeletion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_marked_for_deletion");

                    b.Property<string>("KeycloakSub")
                        .HasColumnType("text")
                        .HasColumnName("keycloak_sub");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakSub")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.UserSearchQueryDigestEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("SearchQueryId")
                        .HasColumnType("integer")
                        .HasColumnName("search_query_id");

                    b.Property<DateTime?>("LastDigestSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_digest_sent_at");

                    b.HasKey("UserId", "SearchQueryId");

                    b.HasIndex("SearchQueryId");

                    b.ToTable("user_search_query_digests", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.UserSearchQueryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("SearchQueryId")
                        .HasColumnType("integer")
                        .HasColumnName("search_query_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SearchQueryId");

                    b.HasIndex("UserId", "SearchQueryId")
                        .IsUnique();

                    b.ToTable("user_search_queries", (string)null);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.SearchQueryEntity", b =>
                {
                    b.HasOne("RecordService.DataAccess.Entities.SourceEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.SearchQueryRecordEntity", b =>
                {
                    b.HasOne("RecordService.DataAccess.Entities.RecordEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecordService.DataAccess.Entities.SearchQueryEntity", null)
                        .WithMany()
                        .HasForeignKey("SearchQueryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.SourceRecordEntity", b =>
                {
                    b.HasOne("RecordService.DataAccess.Entities.RecordEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RecordService.DataAccess.Entities.SourceEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.UserSearchQueryDigestEntity", b =>
                {
                    b.HasOne("RecordService.DataAccess.Entities.SearchQueryEntity", null)
                        .WithMany()
                        .HasForeignKey("SearchQueryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RecordService.DataAccess.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("RecordService.DataAccess.Entities.UserSearchQueryEntity", b =>
                {
                    b.HasOne("RecordService.DataAccess.Entities.SearchQueryEntity", null)
                        .WithMany()
                        .HasForeignKey("SearchQueryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RecordService.DataAccess.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
