version: '3.8'
name: pubtracker
services:
  postgres:
    image: postgres:16-alpine
    container_name: pubtracker_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pubtracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.4
    container_name: pubtracker_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    container_name: pubtracker_web
    restart: unless-stopped
    build: .
    ports:
      - "8000:80"