CREATE TABLE IF NOT EXISTS sources (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    base_url TEXT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS search_queries (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    source_id INTEGER,
    target_url TEXT,
    last_digest_sent_at TIMESTAMPTZ,
    PRIMARY KEY (id),
    UNIQUE (source_id, target_url)
);

CREATE TABLE IF NOT EXISTS records (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doi TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    is_marked_for_deletion BOOLEAN NOT NULL DEFAULT FALSE,
    deletion_requested_at TIMESTAMPTZ,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_search_queries (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER NOT NULL,
    search_query_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    UNIQUE (user_id, search_query_id)
);

CREATE TABLE IF NOT EXISTS source_records (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    record_id INTEGER,
    source_id INTEGER,
    PRIMARY KEY (id),
    UNIQUE (record_id, source_id)
);

CREATE TABLE IF NOT EXISTS search_query_records (
    search_query_id INTEGER,
    record_id INTEGER,
    first_seen_at TIMESTAMPTZ,
    PRIMARY KEY (search_query_id, record_id)
);

ALTER TABLE user_search_queries
    ADD FOREIGN KEY (user_id) REFERENCES users (id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE user_search_queries
    ADD FOREIGN KEY (search_query_id) REFERENCES search_queries (id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE search_queries
    ADD FOREIGN KEY (source_id) REFERENCES sources (id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE source_records
    ADD FOREIGN KEY (source_id) REFERENCES sources (id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE source_records
    ADD FOREIGN KEY (record_id) REFERENCES records (id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE search_query_records
    ADD FOREIGN KEY (search_query_id) REFERENCES search_queries (id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE search_query_records
    ADD FOREIGN KEY (record_id) REFERENCES records (id)
    ON UPDATE NO ACTION ON DELETE NO ACTION;